# Useless assignment to variable - article.
Lint/UselessAssignment:
  Enabled: false

# Line is too long.
Metrics/LineLength:
  Max: 160

# Missing top-level class documentation comment.
Documentation:
  Enabled: false

# include is used at the top level. Use inside class or module.
Style/MixinUsage:
  Enabled: false
